apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2024-03-25T04:10:02Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "42302"
  uid: 5ce6c557-9834-4005-831d-7c6b196c6c4d
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::172582138886:role/argocdprj-eks-nodes-role
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::172582138886:role/AWSReservedSSO_USYD_ROOT_ADMINS_1497d78f09231d1d
      username: mlia5105_admin
  mapUsers: |
    []

